import { AlertCircle, Sparkles } from "lucide-react";

import type { Analysis, Interaction } from "@/api/types";
import { EvidenceChips } from "@/components/EvidenceChips";
import { PriorityBadge } from "@/components/PriorityBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

interface Props {
  analysis: Analysis | null;
  interactions: Interaction[];
  isRefreshing: boolean;
  onHoverEvidence: (id: string | null) => void;
}

const WAITING_LABEL = {
  us: "They are waiting on us",
  customer: "We are waiting on them",
  nobody: "Nothing pending",
};

/** The AI's current read on the relationship: summary, priority and why, next action, open items. */
export function AnalysisPanel({ analysis, interactions, isRefreshing, onHoverEvidence }: Props) {
  if (isRefreshing) return <AnalysisSkeleton />;
  if (!analysis) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-sm text-muted-foreground">
          No analysis yet. Add an interaction or run an analysis.
        </CardContent>
      </Card>
    );
  }
  const { judgment, narrative } = analysis;
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2 text-base">
          <Sparkles className="size-4 text-primary" /> Where things stand
        </CardTitle>
        <PriorityBadge priority={judgment.priority} />
      </CardHeader>
      <CardContent className="space-y-5">
        <p className="leading-relaxed">{narrative.relationship_summary}</p>

        <section className="rounded-md border bg-muted/40 p-3">
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Why it matters · {WAITING_LABEL[judgment.waiting_on]}
          </p>
          <p className="mt-1 text-sm">{narrative.priority_reason}</p>
        </section>

        <section>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Recommended next step
          </p>
          <p className="mt-1 font-medium">{narrative.next_action}</p>
        </section>

        {narrative.open_items.length > 0 && (
          <section>
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Open questions from the customer
            </p>
            <ul className="mt-1 space-y-1 text-sm">
              {narrative.open_items.map((item) => (
                <li key={item} className="flex gap-2">
                  <AlertCircle className="mt-0.5 size-4 shrink-0 text-medium" /> {item}
                </li>
              ))}
            </ul>
          </section>
        )}

        <EvidenceChips
          evidenceIds={narrative.evidence_ids}
          interactions={interactions}
          onHover={onHoverEvidence}
        />

        <p className="text-xs text-muted-foreground">
          {analysis.fallback_used
            ? "Produced by the rule-based fallback because no language model was available."
            : `Generated by ${analysis.generation_provider}${analysis.model ? ` (${analysis.model})` : ""}`}
          {analysis.latency_ms ? ` in ${(analysis.latency_ms / 1000).toFixed(1)}s` : ""} · trigger:{" "}
          {analysis.trigger.replace("_", " ")}
        </p>
      </CardContent>
    </Card>
  );
}

function AnalysisSkeleton() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <Sparkles className="size-4 animate-pulse text-primary" /> Analyzing the new interaction…
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-11/12" />
        <Skeleton className="h-4 w-3/4" />
        <Skeleton className="mt-4 h-16 w-full" />
        <Skeleton className="h-5 w-2/3" />
      </CardContent>
    </Card>
  );
}
